### ISSUE TITLE
"nw" script points to non-existent nw binary

### ISSUE THREAD

**Issue by LongLiveCHIEF** [nwjs/npm-installer#10]
I have tried to install the nw binary with the nw installer several times.  It'a has been successful, however, I can't get either the local, nor the global `nw` script to run.  I keep getting an `ENOENT` error:

    Error: spawn /usr/local/lib/node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
        at child_process.js:1137:20
        at process._tickCallback (node.js:355:11)

the path the script is trying to use is not correct. The same error results either trying to run `npm start` script indicated in `package.json`, and also when i use the `nw` command while in the project.

**Comment by shama** [comment]
Does the binary exist at that path or any parts of it `/usr/local/lib/node_modules/nw/nwjs`?
Which version of `npm` and version of `nw`?

**Comment by LongLiveCHIEF** [comment]
the binary is at `/usr/local/lib/node_modules/nw/bin/nw`, with a symlink at `/usr/local/bin/nw`

npm version is `2.5.1` and nw version is `0.11.6`.  My complete error output is:

```bash
nw.js appears to have failed to download and extract. Attempting to download and extract again...
module.js:338
    throw err;
          ^
Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nw/scripts/install.js:10:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /usr/local/lib/node_modules/nw/nwjs/nwjs.app/Contents/MacOS/nwjs ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)
```

**Comment by shama** [comment]
Ah that might be the problem. `nw` is latest is at `0.12.0-rc1`. Any version below `0.12.0`, you'll need to use the old installer with `npm i nodewebkit@0.11.6`

**Comment by LongLiveCHIEF** [comment]
Any idea why `npm install nw` wouldn't install v0.12.x?

In checking my `package.json`, that's the version that was specified, yet
an older binary was installed.

The old binary was `nw`, whereas the new is `nwjs`.

I re-ran the install removing the npm installed module/clearing npm cache.
I then downloaded 0.12, then deleted the npm installed binary, and created
a symlink in the expected binary location to the new manually downloaded
binary. Now things seem to be working.
