### ISSUE TITLE
nw command fails by error at parse.js in the latest( Mar 30, 2024) version

### ISSUE THREAD

**Issue by hoge1e3** [nwjs/npm-installer#143]
The nw command fails with following message.

```
%  node_modules\.bin\nw test\browser.html
file:///...../node_modules/nw/src/parse.js:44
        options.version = [version, ...prerelease].join('-');
                           ^

ReferenceError: version is not defined
    at parse (file:///.....node_modules/nw/src/parse.js:44:28)
    at cli (file:///...../node_modules/nw/src/cli.js:24:19)
    at file:///...../node_modules/nw/src/cli.js:10:7
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:120:12)

Node.js v21.7.1
```
I took a quick peek at src/parse.js, and sure enough, `version` is not declared.

https://github.com/nwjs/npm-installer/commit/5c936ed71600bfe655367fb15e195698744d8cb1#diff-42f95033dbb9c5068c9cc85ce7c08cf1c22f68199a26bfab67817c63ff804253

**Comment by ayushmanchhabra** [comment]
Just released v0.86.0. Could you verify if it works?
