### ISSUE TITLE
Unable to install nodewebkit@0.10.5

### ISSUE THREAD

**Issue by agirorn** [nwjs/npm-installer#52]
I am unable to install nodewebkit 0.10.5 on Ubuntu Linux.

```shell
my-app git:(master) npm install nodewebkit@0.10.5

> nodewebkit@0.10.5 postinstall /home/agirorn/code/my-app/node_modules/nodewebkit
> node scripts/install.js

stream.js:74
      throw er; // Unhandled stream error in pipe.0.5-linux-x64.tar.gz [          ] 0 %
      ^

Error: invalid tar file
    at Extract.Parse._startEntry (/home/agirorn/code/my-app/node_modules/tar/lib/parse.js:145:13)
    at Extract.Parse._process (/home/agirorn/code/my-app/node_modules/tar/lib/parse.js:127:12)
    at BlockStream.<anonymous> (/home/agirorn/code/my-app/node_modules/tar/lib/parse.js:47:8)
    at emitOne (events.js:77:13)
    at BlockStream.emit (events.js:169:7)
    at BlockStream._emitChunk (/home/agirorn/code/my-app/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/home/agirorn/code/my-app/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/home/agirorn/code/my-app/node_modules/fstream/lib/reader.js:255:34)
    at DirWriter.<anonymous> (/home/agirorn/code/my-app/node_modules/tar/lib/extract.js:57:8)
    at emitNone (events.js:67:13)
npm WARN @nls/technician-app@0.7.0 No repository field.
npm WARN @nls/technician-app@0.7.0 No license field.
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/home/agirorn/.nvm/versions/node/v4.7.0/bin/node" "/home/agirorn/.nvm/versions/node/v4.7.0/bin/npm" "install" "nodewebkit@0.10.5"
npm ERR! node v4.7.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodewebkit@0.10.5 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodewebkit@0.10.5 postinstall script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodewebkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodewebkit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodewebkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/agirorn/code/my-app/npm-debug.log
➜  my-app git:(master) 
```

`npm-debug.log` does not exits.

I am able to download http://dl.node-webkit.org/v0.10.5/node-webkit-v0.10.5-linux-x64.tar.gz in a browser.

`http://dl.node-webkit.org/v0.10.5/node-webkit-v0.10.5-linux-x64.tar.gz` seems to have been moved to `http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-linux-x64.tar.gz`

```shell
my-app git:(master) curl -I http://dl.node-webkit.org/v0.10.5/node-webkit-v0.10.5-linux-x64.tar.gz
HTTP/1.1 301 Moved Permanently
Date: Tue, 20 Dec 2016 15:15:25 GMT
Server: Apache/2.2.22 (Debian)
Location: http://dl.nwjs.io/v0.10.5/node-webkit-v0.10.5-linux-x64.tar.gz
Vary: Accept-Encoding
Content-Type: text/html; charset=iso-8859-1
```

My guess is that the install can't handle the redirect.

**Comment by Mithgol** [comment]
Consider reporting this issue to https://github.com/shama/nodewebkit (which is the repo containing the source code of the `nodewebkit` package).

**Comment by shama** [comment]
The `nodewebkit` package is deprecated in favor of `nw`. Please update and use `npm install nw` instead.

**Comment by agirorn** [comment]
We are using 0.10.5 and need to be able to install that version for some time. When I check out the code that is stored on NPM for nodewebkit@0.10.5 then I get the code from this installer and it seems that code can't handle the redirect that is needed to install nodewebkit.

**Comment by agirorn** [comment]
@Mithgol sorry I misunderstood you I have filed it under https://github.com/shama/nodewebkit.
