### ISSUE TITLE
Crash during startup on Win10 x64

### ISSUE THREAD

**Issue by daintycode** [nwjs/npm-installer#60]
installed it locally, `nw build` in package.json crashed and when installed globally running it via `nw .` it crashes.
Both with `TypeError: Cannot read property 'split' of undefined`

**stdout:**
`
TypeError: Cannot read property 'split' of undefined
    at module.exports (C:\Users\Andy\AppData\Roaming\npm\node_modules\nwjs\lib\old-version.js:2:19)
    at module.exports (C:\Users\Andy\AppData\Roaming\npm\node_modules\nwjs\lib\get-path.js:10:26)
    at Command.module.exports (C:\Users\Andy\AppData\Roaming\npm\node_modules\nwjs\lib\run.js:16:16)
    at Command.listener (C:\Users\Andy\AppData\Roaming\npm\node_modules\nwjs\node_modules\commander\index.js:300:8)
    at emitOne (events.js:115:13)
    at Command.emit (events.js:210:7)
    at Command.parseArgs (C:\Users\Andy\AppData\Roaming\npm\node_modules\nwjs\node_modules\commander\index.js:637:12)
    at Command.parse (C:\Users\Andy\AppData\Roaming\npm\node_modules\nwjs\node_modules\commander\index.js:457:21)
    at Object.<anonymous> (C:\Users\Andy\AppData\Roaming\npm\node_modules\nwjs\nw:64:18)
    at Module._compile (module.js:624:30)
`

Using it downloaded from the website works.

**Comment by Siunaus** [comment]
I have the same problem on macOS 10.13.1 with globally installed by npm

**Comment by Siunaus** [comment]
@daintycode I have resolve this , try this way https://www.npmjs.com/package/nwjs
