### ISSUE TITLE
TypeError: Decompress is not a constructor when using file:// URL

### ISSUE THREAD

**Issue by ZumiKua** [nwjs/npm-installer#77]
````
TypeError: Decompress is not a constructor
    at Object.<anonymous> ([removed]\node_modules\nw\scripts\install.js:99:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
````
It seems that Decompress's API has been changed.

**Comment by baoyu-li** [comment]
Met the same error
It seems like 'decompress' is now just an arrow fuction:
https://github.com/kevva/decompress/blob/74a462a139cc2561b6695e696266c8dc31562d3d/index.js#L76

**Comment by TheJaredWilcurt** [comment]
* What Node version are you on?
* Is this a recent issue?
  * The `decompress` version in `package.json` was set to `^4.2.0` 16 months ago.
* Is this an `npm-installer` issue or an issue with `decompress`?

**Comment by ZumiKua** [comment]
- What Node version are you on?

    Node version: v10.14.2 (windows)
    npm version: 6.4.1

- Is this a recent issue?

    I guess not, decompress changes it's API long ago:
https://github.com/kevva/decompress/commit/4cb6e65146e137ab52f859b6a15dfa8889cf1103#diff-0730bb7c2e8f9ea2438b52e419dd86c9R19
but it seems that @rogerwang just upgrade the dependency without handling the API changes 4a62581bbd4b16ed7806266b1ea00be15fb1b441 

- Is this an `npm-installer` issue or an issue with `decompress`?

    This is a `npm-installer` issue.
